apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: clear-cache
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: thp-disable
  template:
    metadata:
      labels:
        name: thp-disable
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-proc
          hostPath:
            path: /proc
      containers:
        - name: busybox
          image: busybox
          command: {{ .Values.command }}
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
            - name: host-proc
              mountPath: /host-proc
