apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.ReleaseName }}
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: {{ .Values.ReleaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.ReleaseName }}
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/unschedulable
          operator: Exists
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-proc
          hostPath:
            path: /proc
      containers:
        - name: busybox
          image: busybox
          command: {{ toYaml .Values.command  | nindent 12 }}
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
            - name: host-proc
              mountPath: /host-proc

