apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.ReleaseName }}
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: {{ .Values.ReleaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.ReleaseName }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-proc
          hostPath:
            path: /proc
      containers:
        - name: busybox
          image: busybox
          command: ["watch", "-n", "300", "echo", "3", ">", "/host-proc/sys/vm/drop_caches"]
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
            - name: host-proc
              mountPath: /host-proc
