apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    meta.helm.sh/release-name: backend
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-12-11T18:15:58Z"
  generation: 5
  labels:
    app: backend
    app.kubernetes.io/managed-by: Helm
    chart: capillary-base-cc-0.2.13
    deployerid: backend
    heritage: Helm
  name: backend
  namespace: default
  resourceVersion: "28733549"
  uid: 54ac9fc6-dbf6-4bcc-9e03-9a0036edbaf9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
      release: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        buildId: backend
        chart: capillary-base-cc-0.2.13
        checksum/config: 9a9777b5a02691b6c2f7cc5875676298c23594bbf4c95c43940c583155f45bf7
        checksum/credentials: d30c3b9577a4e387105c9bed0a5f795e3437109566596d67c8dbc8e8e5413e2b
        checksum/filecredentials: bfc55f993efec95f5014e8caab50588f8a70f20cad74504467b2af61205eea23
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        iam.amazonaws.com/role: arn:aws:iam::338360549315:role/aws-infra-dev-backend-application-role
      creationTimestamp: null
      labels:
        app: backend
        deployerBuildId: "5.0"
        deployerid: backend
        podSize: small
        release: backend
        resourceAllocationStrategy: GP
    spec:
      containers:
      - env:
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              key: AWS_REGION
              name: backend-configs
        - name: CLUSTER
          valueFrom:
            secretKeyRef:
              key: CLUSTER
              name: backend-configs
        - name: MY_VAR
          valueFrom:
            secretKeyRef:
              key: MY_VAR
              name: backend-configs
        - name: TZ
          valueFrom:
            secretKeyRef:
              key: TZ
              name: backend-configs
        - name: BUILD_ID
          value: "5.0"
        image: 313496281593.dkr.ecr.us-east-1.amazonaws.com/facets/release_stream/qa/backend:latest
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 30
        name: backend
        ports:
        - containerPort: 88
          name: port8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/dumps
          name: dump-vol
        - mountPath: /etc/credentialfiles/
          name: backend-file-credentials-vol
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
      volumes:
      - hostPath:
          path: /var/log/dumps/backend
          type: DirectoryOrCreate
        name: dump-vol
      - name: backend-file-credentials-vol
        secret:
          defaultMode: 420
          secretName: backend-file-credentials
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-12-19T14:10:10Z"
    lastUpdateTime: "2022-12-19T14:10:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-12-20T05:41:13Z"
    lastUpdateTime: "2022-12-20T05:41:35Z"
    message: ReplicaSet "backend-56458995c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
